plugins:
  - jekyll-remote-theme

title: Hash Collision
author:
  name: bo-fey
  email: 93552084+bo-fey@users.noreply.github.com

url: https://hash-collision.com

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/bo-fey" }

show_excerpts: true
