title: Hash Collision
author: bo-fey

description: >-
  Assorted ramblings, devblogs, and whatever
  else I feel like posting on here

# baseurl: /hash-collision
url: https://hash-collision.com

theme: minima

github_username: bo-fey

show_excerpts: true
