plugins:
  - jekyll-remote-theme

title: Hash Collision
author:
  name: bofehlan
  email: 93552084+bofehlan@users.noreply.github.com

url: https://hash-collision.com

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/bofehlan" }

show_excerpts: true
