plugins:
  - jekyll-remote-theme

title: Hash Collision
author:
  name: beauregarde-f
  email: 93552084+beauregarde-f@users.noreply.github.com

url: https://hash-collision.com

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/beauregarde-f" }

show_excerpts: true
